# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Heldt2002 Orthostatic Stress - Circulation PBPK.

Source: biomodels_ebi:MODEL1006230084
Original: https://www.ebi.ac.uk/biomodels/MODEL1006230084
"""
from __future__ import annotations

from typing import Any

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Heldt2002OrthostaticstressCircpbpkModel(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Heldt2002 Orthostatic Stress - Circulation PBPK."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _NON_BIOLOGICAL_OBSERVABLES = {'dummy'}
    _TIME_UNIT = 's'
    _SBML_ID = 'MODEL1006230084'
    _TITLE = 'Heldt2002 Orthostatic Stress - Circulation PBPK'
    _PARAMETER_INPUTS = {'heart_rate': ('HR',
                77.0,
                '1/min',
                'Heart rate (beats per minute). Sets the cardiac pacing frequency.')}
    _MULTIPLIER_INPUTS = {'compliance_scale': (['V_LA_0',
                       'V_LV_0',
                       'V_AO_0',
                       'V_RA_0',
                       'V_RV_0',
                       'V_PA_0',
                       'V_AR_0',
                       'V_AD_0',
                       'V_MU_0',
                       'V_GI_0',
                       'V_LI_0',
                       'V_KI_0',
                       'V_SK_0',
                       'V_OT_0',
                       'V_VE_0',
                       'V_VC_0'],
                      1.0,
                      'dimensionless',
                      'Multiplier on the 16 unstressed compartment volumes (V_*_0). In this lumped '
                      'Heldt2002 model the V_*_0 parameters are the zero-pressure resting volumes '
                      '— scaling them effectively perturbs compartment compliance, NOT total fluid '
                      'volume. Effect on aortic pressure is INVERSE: lower compliance_scale (e.g. '
                      '0.5) gives higher pressure (less reservoir capacity); higher (e.g. 2.0) '
                      'gives lower pressure. This is the strongest knob for moving aortic_pressure '
                      'in the model.'),
 'peripheral_resistance_scale': (['R_AR', 'R_AD', 'R_MU', 'R_GI', 'R_LI', 'R_KI', 'R_SK', 'R_OT'],
                                 1.0,
                                 'dimensionless',
                                 'Multiplier on systemic peripheral resistances (R_AR, R_AD, and '
                                 'the 6 tissue beds). Values > 1 represent vasoconstriction.')}
    _HEADLINE_OUTPUTS = {'aortic_flow': ('F_AOalways',
                 'mL/s',
                 'Steady aortic flow. Proxy for cardiac output during the simulation window.'),
 'aortic_pressure': ('P_AO',
                     'mmHg',
                     'Aortic pressure waveform. Standard cardiology readout, proxy for arterial '
                     'pressure.')}
    _HEADLINE_WINDOW_S = 5.0
    def visualisation_aux_schema(self) -> dict[str, str]:
        return {"phase_x": "float", "phase_y": "float", "heart_rate_bpm": "float"}

    def visualisation_aux_description(self) -> str:
        return 'Internal pressure-volume payload for the dedicated visualisation model.'

    def visualisation_extra_selections(self) -> list[str]:
        return ['P_LV']

    def _heart_rate_bpm(self) -> float:
        if self._runner is not None:
            try:
                return float(self._runner["HR"])
            except (KeyError, ValueError, TypeError, RuntimeError):
                try:
                    return float(self._runner["hrf"]) * 60.0
                except (KeyError, ValueError, TypeError, RuntimeError):
                    pass
        return 60.0

    def visualisation_aux_payload(self, t: float, latest: dict[str, float]) -> dict[str, Any]:
        return {
            "phase_x": float(latest.get("V_LV", 0.0)),
            "phase_y": float(latest.get("P_LV", 0.0)),
            "heart_rate_bpm": float(self._heart_rate_bpm()),
        }

    def __init__(
        self,
        model_path: str = 'data/MODEL1006230084.xml',
        integration_step: float = 0.05,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
