# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Heldt2002 Orthostatic Stress - Lumped Parameter Circulation.

Source: biomodels_ebi:MODEL1006230113
Original: https://www.ebi.ac.uk/biomodels/MODEL1006230113
"""
from __future__ import annotations

from typing import Any

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Heldt2002OrthostaticstressLpcModel(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Heldt2002 Orthostatic Stress - Lumped Parameter Circulation."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _NON_BIOLOGICAL_OBSERVABLES = {'dummy'}
    _TIME_UNIT = 's'
    _SBML_ID = 'MODEL1006230113'
    _TITLE = 'Heldt2002 Orthostatic Stress - Lumped Parameter Circulation'
    _PARAMETER_INPUTS = {'heart_rate': ('HR',
                77.0,
                '1/min',
                'Heart rate (beats per minute). Sets the cardiac pacing frequency.'),
 'peak_lv_elastance': ('Emaxlv',
                       5.6,
                       'mmHg/mL',
                       'Peak left ventricle elastance. Higher values = stronger contractility.')}
    _MULTIPLIER_INPUTS = {}
    _HEADLINE_OUTPUTS = {'cardiac_output': ('COutput', 'mL/min', 'Cardiac output. Volume of blood ejected per unit time.'),
 'mean_arterial_pressure': ('MAP',
                            'mmHg',
                            'Mean arterial pressure. The canonical clinical readout.')}
    _HEADLINE_WINDOW_S = 5.0
    def visualisation_aux_schema(self) -> dict[str, str]:
        return {"phase_x": "float", "phase_y": "float", "heart_rate_bpm": "float"}

    def visualisation_aux_description(self) -> str:
        return 'Internal pressure-volume payload for the dedicated visualisation model.'

    def visualisation_extra_selections(self) -> list[str]:
        return ['Plv']

    def _heart_rate_bpm(self) -> float:
        if self._runner is not None:
            try:
                return float(self._runner["HR"])
            except (KeyError, ValueError, TypeError, RuntimeError):
                try:
                    return float(self._runner["hrf"]) * 60.0
                except (KeyError, ValueError, TypeError, RuntimeError):
                    pass
        return 60.0

    def visualisation_aux_payload(self, t: float, latest: dict[str, float]) -> dict[str, Any]:
        return {
            "phase_x": float(latest.get("Vlv", 0.0)),
            "phase_y": float(latest.get("Plv", 0.0)),
            "heart_rate_bpm": float(self._heart_rate_bpm()),
        }

    def __init__(
        self,
        model_path: str = 'data/MODEL1006230113.xml',
        integration_step: float = 0.05,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
