# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Koo2013 Integrated Shear-Stress Induced NO Production.

Source: biomodels_ebi:BIOMD0000000468
Original: https://www.ebi.ac.uk/biomodels/BIOMD0000000468
"""
from __future__ import annotations

from typing import Any

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Koo2013IntegratedShearStressNoProductionModel(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Koo2013 Integrated Shear-Stress Induced NO Production."""

    _OBSERVABLE_STRATEGY = 'species'
    _NON_BIOLOGICAL_OBSERVABLES = {'dummy'}
    _TIME_UNIT = 's'
    _SBML_ID = 'BIOMD0000000468'
    _TITLE = 'Koo2013 Integrated Shear-Stress Induced NO Production'
    _PARAMETER_INPUTS = {'stimulus_intensity': ('k1',
                        0.0012,
                        '1/s',
                        'Mechanotransduction stimulus intensity. In this published BioModels SBML '
                        "(BIOMD0000000468) the 'Shear Stress' species is decorative — it is not "
                        'kinetically wired. Instead, the modeller encoded the stimulus through the '
                        'rate constant k1 of the IP3-producing reaction (re5), which drives the '
                        "full chain through Ca2+, eNOS, and NO production. The SBML's calibrated "
                        'baseline is 0.0012; values above that mimic stronger shear stress.')}
    _MULTIPLIER_INPUTS = {}
    _HEADLINE_OUTPUTS = {'active_eNOS': ('s45', 'substance', 'Active eNOS-CaM-Ca4 complex.'),
 'cytosolic_calcium': ('s3', 'substance', 'Cytosolic Ca2+ amount.'),
 'nitric_oxide': ('s64', 'substance', 'Nitric oxide (NO) amount.')}
    _HEADLINE_WINDOW_S = 60.0

    def __init__(
        self,
        model_path: str = 'data/BIOMD0000000468.xml',
        integration_step: float = 1.0,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
