# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Koo2013 Shear-Stress Induced Calcium Influx and eNOS Activation.

Source: biomodels_ebi:BIOMD0000000464
Original: https://www.ebi.ac.uk/biomodels/BIOMD0000000464
"""
from __future__ import annotations

from typing import Any

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Koo2013ShearStressCalciumInfluxModel(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Koo2013 Shear-Stress Induced Calcium Influx and eNOS Activation."""

    _OBSERVABLE_STRATEGY = 'species'
    _NON_BIOLOGICAL_OBSERVABLES = {'dummy'}
    _TIME_UNIT = 's'
    _SBML_ID = 'BIOMD0000000464'
    _TITLE = 'Koo2013 Shear-Stress Induced Calcium Influx and eNOS Activation'
    _PARAMETER_INPUTS = {'stimulus_intensity': ('k1',
                        0.0006,
                        '1/s',
                        'Mechanotransduction stimulus intensity. In this published BioModels SBML '
                        "(BIOMD0000000464) the 'Shear Stress' species is decorative — it is not "
                        'kinetically wired. Instead, the modeller encoded the stimulus through the '
                        'rate constant k1 of the IP3-producing reaction (re5). Setting k1=0 '
                        "produces a quiescent cell (no IP3, no calcium release); the SBML's "
                        'calibrated baseline is 0.0006; values above that mimic stronger shear '
                        'stress.')}
    _MULTIPLIER_INPUTS = {}
    _HEADLINE_OUTPUTS = {'cytosolic_calcium': ('s3',
                       'substance',
                       'Cytosolic Ca2+ amount. Headline downstream readout of shear-stress '
                       'signalling.'),
 'ip3': ('s6',
         'substance',
         'IP3 (inositol 1,4,5-trisphosphate) amount. Second-messenger driving Ca2+ store release.')}
    _HEADLINE_WINDOW_S = 60.0

    def __init__(
        self,
        model_path: str = 'data/BIOMD0000000464.xml',
        integration_step: float = 1.0,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
