# Generated by scripts/refactor_labs.py - safe to edit
"""Tests for the Koo2013 Integrated Shear-Stress Induced NO Production wrapper."""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest
import yaml


_MODEL_DIR = Path(__file__).resolve().parents[1]
_LAB_DIR = _MODEL_DIR.parent
_WRAPPER_PATH = _MODEL_DIR / "src" / "koo2013_integrated_shear_stress_no_production.py"


def _find_bsim_src(start: Path) -> Path | None:
    for parent in [start, *start.parents]:
        for candidate in (parent / "biosim" / "src", parent / "bsim-active" / "biosim" / "src"):
            if (candidate / "biosim").is_dir():
                return candidate
    return None


def _load_wrapper():
    bsim_src = _find_bsim_src(_MODEL_DIR)
    if bsim_src is not None and str(bsim_src) not in sys.path:
        sys.path.insert(0, str(bsim_src))
    # Load by file path so labs that share the package name `src` do not
    # collide in sys.modules when pytest collects them all in one session.
    unique_name = f"koo2013_integrated_shear_stress_no_production__lab_module"
    spec = importlib.util.spec_from_file_location(unique_name, _WRAPPER_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules[unique_name] = module
    spec.loader.exec_module(module)
    return module


_wrapper = _load_wrapper()
Koo2013IntegratedShearStressNoProductionModel = _wrapper.Koo2013IntegratedShearStressNoProductionModel


def _advance_or_skip(module, start: float, end: float) -> None:
    try:
        module.advance_window(start, end)
    except (ImportError, ModuleNotFoundError) as exc:
        pytest.skip(f"Optional runtime dependency missing: {exc}")


def test_instantiation():
    module = Koo2013IntegratedShearStressNoProductionModel()
    assert module.integration_step > 0
    assert isinstance(module.inputs(), dict)
    assert "integration_step" in module.inputs()
    assert {"state", "summary"}.issubset(set(module.outputs().keys()))


def test_advance_accumulates_history():
    module = Koo2013IntegratedShearStressNoProductionModel()
    _advance_or_skip(module, 0.0, 600.0)
    assert len(module._history) > 1, "advance_window must accumulate trajectory points"
    assert module._observables, "observables must be discovered after setup"
    assert {"state", "summary"}.issubset(set(module.get_outputs().keys()))


def test_visualize_shape():
    module = Koo2013IntegratedShearStressNoProductionModel()
    _advance_or_skip(module, 0.0, 600.0)
    visuals = module.visualize()
    assert isinstance(visuals, list) and len(visuals) >= 3
    renders = {v["render"] for v in visuals}
    assert renders == {"timeseries", "bar", "table"}
    assert sum(1 for v in visuals if v["render"] == "timeseries") >= 1
    table = next(v for v in visuals if v["render"] == "table")
    assert table["data"]["columns"] == ["Question", "Answer"]
    assert len(table["data"]["rows"]) >= 4


def test_lab_yaml_io_matches_module():
    lab = yaml.safe_load((_LAB_DIR / "lab.yaml").read_text())
    declared_inputs = {entry["name"] for entry in lab["io"]["inputs"]}
    declared_outputs = {entry["name"] for entry in lab["io"]["outputs"]}
    module = Koo2013IntegratedShearStressNoProductionModel()
    assert declared_inputs == set(module.inputs().keys())
    assert declared_outputs == set(module.outputs().keys())
