# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Heldt2002 Orthostatic Stress - Heart.

Source: biomodels_ebi:MODEL1006230103
Original: https://www.ebi.ac.uk/biomodels/MODEL1006230103
"""
from __future__ import annotations

import math
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Dict, List, Optional, TYPE_CHECKING

import biosim
from biosim.signals import (
    AcceptedSignalProfile,
    BioSignal,
    RecordSignal,
    ScalarSignal,
    SignalSpec,
)

if TYPE_CHECKING:  # pragma: no cover
    from biosim.visuals import VisualSpec


_OBSERVABLE_STRATEGY = "rateRule"

# BioModels exports occasionally carry placeholder parameters with no
# biological meaning (e.g. a `dummy` rate-rule variable left over from the
# curator's scratch work). They survive into the SBML and would otherwise
# show up in the lab's outputs and visualizations as noise. Names listed
# here are silently dropped during observable discovery.
_NON_BIOLOGICAL_OBSERVABLES = {"dummy"}

_TIME_UNIT = "s"
_SBML_ID = "MODEL1006230103"
_TITLE = "Heldt2002 Orthostatic Stress - Heart"


# Anatomical / functional grouping for visualization.
# Mapping is based purely on the SBML variable naming convention used by the
# Heldt2002 family of models. Variables that don't match any group fall through
# to "other" and are still rendered, just under a generic label.
_GROUP_META = {
    "cardiac_chambers": (
        "Cardiac chamber volumes",
        "How does atrial and ventricular filling change during the orthostatic stress event?",
    ),
    "central_vessels": (
        "Central vessel volumes",
        "How do aortic, pulmonary, and coronary trunk volumes redistribute when posture shifts?",
    ),
    "systemic_arteries": (
        "Systemic arterial volumes",
        "How does arterial / arteriolar tone respond to the simulated tilt?",
    ),
    "peripheral_tissue": (
        "Peripheral tissue volumes",
        "Where does blood pool - muscle, gut, liver, kidney, skin, or other tissue?",
    ),
    "veins": (
        "Venous return volumes",
        "How quickly does the venous reservoir respond to the orthostatic stress event?",
    ),
    "aortic_flow": (
        "Aortic flow",
        "What does the aortic flow signal look like before and after the tilt?",
    ),
    "substrate_concentration": (
        "Substrate concentrations by compartment",
        "How is the dissolved PBPK tracer redistributed across compartments over time?",
    ),
    "koo_input": (
        "Mechanical inputs and timers",
        "What is the shear-stress input doing, and how does the model's internal time tracker evolve?",
    ),
    "koo_calcium": (
        "Calcium subsystem (Ca²⁺ pools, IP₃, calmodulin)",
        "How do extracellular, stored, cytosolic, and buffered Ca²⁺ pools shift, and how does IP₃-driven release propagate through calmodulin?",
    ),
    "koo_mechano": (
        "Mechanosensor cascade (FAK / Src / Shc / Ras / adapters)",
        "How does the focal-adhesion kinase pathway transduce mechanical shear into the upstream signalling cascade?",
    ),
    "koo_pi3k_akt": (
        "PI3K / AKT signalling axis",
        "How does shear-stimulated PI3K activate AKT through PI3P and PDK kinases?",
    ),
    "koo_mapk": (
        "MAPK cascade (MEKK1 / JNKK / JNK) and transcription factors",
        "How does the MAPK cascade phosphorylate downstream and activate AP-1 and KLF2 transcriptional responses?",
    ),
    "koo_enos_chain": (
        "eNOS activation chain (eNOS · CaM · Ca₄ · Hsp90 complexes)",
        "How does the eNOS enzyme assemble with calmodulin, calcium, and Hsp90 into its active complex?",
    ),
    "koo_no": (
        "Nitric oxide production",
        "How quickly does the active eNOS complex produce nitric oxide from L-arginine?",
    ),
    "koo_phosphatase": (
        "Regulatory phosphatases (PP2A, PTEN)",
        "How do the deactivating phosphatases respond as the upstream cascade ramps up?",
    ),
    "lpc_central_vessels": (
        "Aortic and pulmonary trunk volumes",
        "How do the proximal and distal aortic and pulmonary segments fill across each cardiac cycle?",
    ),
    "lpc_pulmonary_perfusion": (
        "Pulmonary perfusion (capillary and venous)",
        "How do pulmonary capillaries and pulmonary veins fill as blood traverses the lungs?",
    ),
    "lpc_systemic_perfusion": (
        "Systemic perfusion (arterial, capillary, venous, vena cava)",
        "How do the systemic arterial tree, capillary bed, peripheral veins, and vena cava share the circulating volume?",
    ),
    "lpc_coronary_perfusion": (
        "Coronary microcirculation",
        "How does perfusion distribute across the eight coronary subcompartments (epicardial, subendocardial, capillary, atrial and ventricular zones)?",
    ),
    "lpc_blood_flows": (
        "Aortic and pulmonary flow signals",
        "What are the proximal and distal aortic and pulmonary artery flow waveforms over the cardiac cycle?",
    ),
    "lpc_blood_pressures": (
        "Pressure waveforms",
        "How do mean arterial pressure and aortic perfusion pressure evolve through the cycle?",
    ),
    "other": (
        "Other observables",
        "How do the remaining observed variables evolve over time?",
    ),
}


def _group_observable(name: str, display_name: Optional[str] = None) -> str:
    """Map an observable to a visualization group.

    Three taxonomies, checked in order:
    - Endothelial mechanotransduction (Koo2013 family) — keyed by the SBML
      name= attribute (display_name) since raw ids are opaque (s1..s79).
    - Heldt2002 circulation-PBPK family — UPPERCASE compartment codes
      separated by underscores (V_LV, sub_X_AO, F_AOalways).
    - Heldt2002 LPC family — lowercase compartment codes appended directly
      (Vlv, Faod, MAP, Vcor*).
    """
    # 1. Endothelial-mechanotransduction (uses SBML display name).
    if display_name and display_name in _KOO2013_GROUP_LOOKUP:
        return _KOO2013_GROUP_LOOKUP[display_name]
    # 2. circpbpk family (raw id with underscore separators).
    if name.startswith("sub_X_"):
        return "substrate_concentration"
    if name.startswith("F_AO"):
        return "aortic_flow"
    if name.startswith("V_"):
        suffix = name[2:]
        if suffix in {"LA", "LV", "RA", "RV"}:
            return "cardiac_chambers"
        if suffix in {"AO", "PA", "CO", "CR", "CRtissue"}:
            return "central_vessels"
        if suffix in {"AR", "AD"}:
            return "systemic_arteries"
        if suffix in {"MU", "GI", "LI", "KI", "SK", "OT"}:
            return "peripheral_tissue"
        if suffix in {"VE", "VC", "Pa", "PC", "PV"}:
            return "veins"
    # 3. LPC family (lookup on the full id).
    if name in _LPC_GROUP_LOOKUP:
        return _LPC_GROUP_LOOKUP[name]
    return "other"

# Endothelial mechanotransduction grouping (Koo2013 family). Keyed by the
# SBML <species name="..."> attribute, since the raw ids are opaque (s1, s2,
# ..., s79). Resolution happens in _group_observable via the lifted display
# name from _observable_display_names.
_KOO2013_GROUP_LOOKUP = {
    # Inputs / timers
    "Shear Stress": "koo_input",
    "Time": "koo_input",
    "TimeT": "koo_input",
    "pre_time": "koo_input",
    # Calcium subsystem
    "Ca_ex": "koo_calcium",
    "Ca_s": "koo_calcium",
    "Ca_c": "koo_calcium",
    "Ca_B": "koo_calcium",
    "IP3": "koo_calcium",
    "PIP2": "koo_calcium",
    "Calmodulin": "koo_calcium",
    "CaM-Ca2": "koo_calcium",
    "CaM-Ca4": "koo_calcium",
    # Mechanosensor cascade
    "FAK": "koo_mechano",
    "p-FAK": "koo_mechano",
    "p-FAK:Shc": "koo_mechano",
    "p-FAK:p-Shc": "koo_mechano",
    "p-FAK:p-Shc:Grb2:Sos": "koo_mechano",
    "Shc": "koo_mechano",
    "p-Shc": "koo_mechano",
    "p-Shc:Grb2:Sos": "koo_mechano",
    "Grb2:Sos": "koo_mechano",
    "Ras:GDP": "koo_mechano",
    "Ras:GTP": "koo_mechano",
    "Src": "koo_mechano",
    "p-Src": "koo_mechano",
    # PI3K / AKT signalling
    "PI3K": "koo_pi3k_akt",
    "p-PI3K": "koo_pi3k_akt",
    "PI3P": "koo_pi3k_akt",
    "AKT": "koo_pi3k_akt",
    "AKT:PI3P": "koo_pi3k_akt",
    "p-AKT:PI3P": "koo_pi3k_akt",
    "pp-AKT:PI3P": "koo_pi3k_akt",
    "PDK1": "koo_pi3k_akt",
    "PDK1_cyto": "koo_pi3k_akt",
    "PDK2": "koo_pi3k_akt",
    # MAPK cascade
    "MEKK1": "koo_mapk",
    "p-MEKK1": "koo_mapk",
    "JNKK": "koo_mapk",
    "p-JNKK": "koo_mapk",
    "pp-JNKK": "koo_mapk",
    "JNK": "koo_mapk",
    "p-JNK": "koo_mapk",
    "pp-JNK": "koo_mapk",
    "AP-1": "koo_mapk",
    "aAP-1": "koo_mapk",
    "KLF2": "koo_mapk",
    # eNOS / Hsp90 chain
    "eNOS": "koo_enos_chain",
    "eNOS-CaM-Ca2": "koo_enos_chain",
    "eNOS-CaM-Ca4": "koo_enos_chain",
    "eNOS-Cav-1": "koo_enos_chain",
    "Hsp90": "koo_enos_chain",
    "Hsp90-eNOS": "koo_enos_chain",
    "Hsp90-eNOS-CaM-Ca2": "koo_enos_chain",
    "Hsp90-eNOS-CaM-Ca4": "koo_enos_chain",
    "Hsp90-p-eNOS": "koo_enos_chain",
    "Hsp90-p-eNOS-CaM-Ca2": "koo_enos_chain",
    "Hsp90-p-eNOS-CaM-Ca4": "koo_enos_chain",
    # NO production
    "NO": "koo_no",
    "L-Arg": "koo_no",
    # Regulatory phosphatases
    "PP2A": "koo_phosphatase",
    "PTEN": "koo_phosphatase",
}



# Anatomical labels for the standard Heldt2002 compartment codes. Codes that
# don't appear here (or live in non-Heldt2002 labs) fall back to the raw SBML
# id, which is fine since other labs in this generator use names that are
# already readable (e.g. calcium_cyt, eNOS).
_COMPARTMENT_NAMES = {
    "LA": "Left Atrium",
    "LV": "Left Ventricle",
    "RA": "Right Atrium",
    "RV": "Right Ventricle",
    "AO": "Aorta",
    "AR": "Systemic Arteries",
    "AD": "Abdominal Bed",
    "CO": "Coronary Trunk",
    "CR": "Coronary Arterioles",
    "CRtissue": "Coronary Microvasculature",
    "MU": "Muscle",
    "GI": "Gastrointestinal Bed",
    "LI": "Liver",
    "KI": "Kidney",
    "SK": "Skin",
    "OT": "Other Tissue",
    "VE": "Systemic Veins",
    "VC": "Vena Cava",
    "PA": "Pulmonary Artery",
    "Pa": "Pulmonary Arterioles",
    "PC": "Pulmonary Capillaries",
    "PV": "Pulmonary Veins",
}


# Hand-authored labels for the Shorten2007 skeletal-muscle fatigue model.
# The SBML stores name=id for every parameter, so there is nothing for the
# generic SBML-name lookup to lift. These labels translate the published
# biophysics shorthand (Hodgkin-Huxley gating variables, RyR channel states,
# SR/cytosolic calcium, ATP/Mg complexes, cross-bridge states) into something
# a non-electrophysiologist can read.
_SHORTEN2007_LABELS = {
    # Membrane potentials
    "vS": "Sarcolemma membrane potential",
    "vT": "T-tubule membrane potential",
    # Ion concentrations
    "K_i": "Intracellular K+",
    "K_t": "T-tubule K+",
    "K_e": "Extracellular K+",
    "Na_i": "Intracellular Na+",
    "Na_t": "T-tubule Na+",
    "Na_e": "Extracellular Na+",
    # Sarcolemma gating variables (Hodgkin-Huxley)
    "n": "Sarcolemma K+ activation gate (n)",
    "h_K": "Sarcolemma K+ inactivation gate (h_K)",
    "m": "Sarcolemma Na+ activation gate (m)",
    "h": "Sarcolemma Na+ inactivation gate (h)",
    "S": "Sarcolemma K+ slow gating (S)",
    # T-tubule gating variables
    "n_t": "T-tubule K+ activation gate",
    "h_K_t": "T-tubule K+ inactivation gate",
    "m_t": "T-tubule Na+ activation gate",
    "h_t": "T-tubule Na+ inactivation gate",
    "S_t": "T-tubule K+ slow gating",
    # RyR channel states (calcium-bound closed/open occupancies)
    "C_0": "RyR closed, 0 Ca-bound",
    "C_1": "RyR closed, 1 Ca-bound",
    "C_2": "RyR closed, 2 Ca-bound",
    "C_3": "RyR closed, 3 Ca-bound",
    "C_4": "RyR closed, 4 Ca-bound",
    "O_0": "RyR open, 0 Ca-bound",
    "O_1": "RyR open, 1 Ca-bound",
    "O_2": "RyR open, 2 Ca-bound",
    "O_3": "RyR open, 3 Ca-bound",
    "O_4": "RyR open, 4 Ca-bound",
    # Calcium pools
    "Ca_1": "Cytosolic Ca2+ (compartment 1)",
    "Ca_2": "Cytosolic Ca2+ (compartment 2)",
    "Ca_SR1": "SR Ca2+ (compartment 1)",
    "Ca_SR2": "SR Ca2+ (compartment 2)",
    "Ca_T_2": "Troponin-bound Ca2+",
    "Ca_CaT2": "Doubly-Ca-bound troponin",
    # Buffer-bound calcium / magnesium
    "Ca_P1": "Parvalbumin-Ca2+ (compartment 1)",
    "Ca_P2": "Parvalbumin-Ca2+ (compartment 2)",
    "Mg_P1": "Parvalbumin-Mg2+ (compartment 1)",
    "Mg_P2": "Parvalbumin-Mg2+ (compartment 2)",
    "Ca_Cs1": "Calsequestrin-Ca2+ (compartment 1)",
    "Ca_Cs2": "Calsequestrin-Ca2+ (compartment 2)",
    # ATP / Mg complexes
    "Ca_ATP1": "Ca-ATP (compartment 1)",
    "Ca_ATP2": "Ca-ATP (compartment 2)",
    "Mg_ATP1": "Mg-ATP (compartment 1)",
    "Mg_ATP2": "Mg-ATP (compartment 2)",
    "ATP1": "Free ATP (compartment 1)",
    "ATP2": "Free ATP (compartment 2)",
    "Mg1": "Free Mg2+ (compartment 1)",
    "Mg2": "Free Mg2+ (compartment 2)",
    # Cross-bridge states (actomyosin cycle)
    "D_0": "Detached cross-bridge (D_0)",
    "D_1": "Detached cross-bridge (D_1)",
    "D_2": "Detached cross-bridge (D_2)",
    "A_1": "Attached cross-bridge (A_1)",
    "A_2": "Attached cross-bridge (A_2)",
    # Inorganic phosphate pools
    "P": "Inorganic phosphate (cytosol)",
    "P_SR": "Inorganic phosphate (SR)",
    "P_C_SR": "Precipitated phosphate (SR)",
}


# Friendly labels for Koo et al. 2013 endothelial mechanotransduction species.
# The SBML name= attributes are biochemist-style abbreviations (Ca_ex, IP3,
# eNOS-CaM-Ca4); these expand them with explanatory annotations so a non-
# specialist reading the canvas can tell what's being measured.
_KOO2013_LABELS = {
    # Calcium subsystem
    "Ca_ex": "Extracellular calcium (Ca²⁺)",
    "Ca_s":  "Stored calcium (ER lumen)",
    "Ca_c":  "Cytosolic calcium (Ca²⁺)",
    "Ca_B":  "Buffered calcium (protein-bound)",
    "Calmodulin": "Calmodulin",
    "CaM-Ca2": "Calmodulin·Ca₂ complex",
    "CaM-Ca4": "Calmodulin·Ca₄ complex",
    # Phosphoinositide / IP3 signalling
    "PIP2": "PIP₂ (phosphatidylinositol 4,5-bisphosphate)",
    "IP3":  "IP₃ (inositol 1,4,5-trisphosphate)",
    "PI3K": "PI3K (phosphoinositide 3-kinase)",
    "p-PI3K": "PI3K (phosphorylated)",
    "PI3P": "PI3P (phosphatidylinositol 3-phosphate)",
    # AKT / PDK
    "AKT": "AKT (protein kinase B)",
    "AKT:PI3P":      "AKT·PI3P complex",
    "p-AKT:PI3P":    "AKT·PI3P (singly phosphorylated)",
    "pp-AKT:PI3P":   "AKT·PI3P (doubly phosphorylated, active)",
    "PDK1":      "PDK1 (membrane)",
    "PDK1_cyto": "PDK1 (cytosolic)",
    "PDK2":      "PDK2 (3-phosphoinositide-dependent kinase 2)",
    # eNOS / Hsp90 complex chain
    "eNOS": "eNOS (endothelial nitric oxide synthase)",
    "eNOS-CaM-Ca2": "eNOS·CaM·Ca₂ complex",
    "eNOS-CaM-Ca4": "eNOS·CaM·Ca₄ complex (active)",
    "eNOS-Cav-1":   "eNOS·caveolin-1 (inhibited)",
    "Hsp90":              "Hsp90 (heat shock protein 90)",
    "Hsp90-eNOS":         "Hsp90·eNOS",
    "Hsp90-eNOS-CaM-Ca2": "Hsp90·eNOS·CaM·Ca₂",
    "Hsp90-eNOS-CaM-Ca4": "Hsp90·eNOS·CaM·Ca₄ (active)",
    "Hsp90-p-eNOS":         "Hsp90·p-eNOS",
    "Hsp90-p-eNOS-CaM-Ca2": "Hsp90·p-eNOS·CaM·Ca₂",
    "Hsp90-p-eNOS-CaM-Ca4": "Hsp90·p-eNOS·CaM·Ca₄ (peak active)",
    # NO production
    "NO":    "Nitric oxide (NO)",
    "L-Arg": "L-arginine",
    # MAPK pathway
    "MEKK1":   "MEKK1 (MAPK kinase kinase)",
    "p-MEKK1": "MEKK1 (phosphorylated)",
    "JNKK":    "JNKK (MAPK kinase, MKK4/7)",
    "p-JNKK":  "JNKK (singly phosphorylated)",
    "pp-JNKK": "JNKK (doubly phosphorylated, active)",
    "JNK":     "JNK (c-Jun N-terminal kinase)",
    "p-JNK":   "JNK (singly phosphorylated)",
    "pp-JNK":  "JNK (doubly phosphorylated, active)",
    # Transcription
    "AP-1":  "AP-1 (transcription factor)",
    "aAP-1": "AP-1 (active)",
    "KLF2":  "KLF2 (Krüppel-like factor 2)",
    # Mechano-sensor / adapters
    "FAK":   "FAK (focal adhesion kinase)",
    "p-FAK": "FAK (autophosphorylated)",
    "p-FAK:Shc":            "p-FAK·Shc complex",
    "p-FAK:p-Shc":          "p-FAK·p-Shc complex",
    "p-FAK:p-Shc:Grb2:Sos": "p-FAK·p-Shc·Grb2·Sos signalling complex",
    "Shc":              "Shc adapter protein",
    "p-Shc":            "Shc (phosphorylated)",
    "p-Shc:Grb2:Sos":   "p-Shc·Grb2·Sos complex",
    "Grb2:Sos":         "Grb2·Sos complex",
    # GTPase / kinases / phosphatases
    "Ras:GDP": "Ras·GDP (inactive)",
    "Ras:GTP": "Ras·GTP (active)",
    "Src":   "Src kinase",
    "p-Src": "Src (phosphorylated, active)",
    "PP2A":  "PP2A (protein phosphatase 2A)",
    "PTEN":  "PTEN (lipid phosphatase)",
    # Inputs / internal
    "Shear Stress": "Shear stress (mechanical input)",
    "Time":     "Simulation time",
    "TimeT":    "Step timer (model internal)",
    "pre_time": "Pre-step time (model internal)",
}


# Friendly labels for Heldt2002 heart-only submodel observables that aren't
# covered by the cardiovascular compartment-code mapping. The heart submodel's
# rateRules are dominated by a placeholder and the meaningful state lives in
# assignment rules; these names label those assignment-rule outputs.
_HELDT2002_LABELS = {
    # Heart submodel (assignment-rule observables)
    "hrf":      "Heart rate frequency (1/s)",
    "beattime": "Beat phase time",
    "Ts":       "Systolic duration",
    "E_LV":     "Left ventricle elastance",
    # LPC submodel (lumped-parameter circulation) - separate naming scheme
    # from the main circpbpk model. Codes are assignment-rule outputs for
    # flows (F*), pressures (P*, MAP), and compartment volumes (V*).
    "Faod": "Aortic flow (distal, lower body)",
    "Faop": "Aortic flow (proximal, upper body)",
    "Fpad": "Pulmonary artery flow (distal)",
    "Fpap": "Pulmonary artery flow (proximal)",
    "MAP":   "Mean arterial pressure",
    "Paopc": "Aortic pressure (proximal compartment)",
    # Cardiac chambers (LPC naming)
    "Vla": "Left atrium volume",
    "Vlv": "Left ventricle volume",
    "Vra": "Right atrium volume",
    "Vrv": "Right ventricle volume",
    # Aorta
    "Vaod": "Aorta volume (distal, lower body)",
    "Vaop": "Aorta volume (proximal, upper body)",
    # Pulmonary loop
    "Vpa":  "Pulmonary artery volume",
    "Vpad": "Pulmonary artery volume (distal)",
    "Vpap": "Pulmonary artery volume (proximal)",
    "Vpc":  "Pulmonary capillary volume",
    "Vpv":  "Pulmonary vein volume",
    # Systemic
    "Vsa":  "Systemic artery volume",
    "Vsap": "Systemic artery volume (proximal)",
    "Vsc":  "Systemic capillary volume",
    "Vsv":  "Systemic vein volume",
    "Vvc":  "Vena cava volume",
    # Coronary subsystem (some sub-compartment subdivisions are inferred from
    # naming; precise anatomical assignment for the `cor` family would need a
    # cross-check against the Heldt 2002 LPC paper's compartment diagram).
    "Vcorao":  "Coronary arterial volume",
    "Vcorea":  "Coronary epicardial arteriolar volume",
    "Vcorcap": "Coronary capillary volume",
    "Vcorev":  "Coronary epicardial venular volume",
    "Vcorla":  "Coronary - left atrial perfusion",
    "Vcorlv":  "Coronary - left ventricular perfusion",
    "Vcorsa":  "Coronary subendocardial arteriolar volume",
    "Vcorsv":  "Coronary subendocardial venular volume",
}



# ---- Lab-specific physiological inputs and outputs ----
_PARAMETER_INPUTS = {
    'heart_rate': ('HR', 70.0, '1/min', 'Heart rate (beats per minute). Sets the cardiac pacing frequency.'),
    'systolic_elastance': ('Esys', 5.6, 'mmHg/mL', 'Peak systolic LV elastance. Higher values = stronger contractility.'),
    'diastolic_elastance': ('Edia', 0.19, 'mmHg/mL', 'Diastolic LV elastance. Sets the chamber compliance during filling.'),
}
_MULTIPLIER_INPUTS = {
}
_HEADLINE_OUTPUTS = {
    'elastance': ('E_LV', 'mmHg/mL', 'Time-varying left ventricle elastance. The headline output of the contractility model.'),
}

# Time window (in seconds) over which headline scalars are averaged.
# Smooths waveform-style observables; harmless for slow signals.
_HEADLINE_WINDOW_S = 2.0


# ---- Phase portrait: parametric loop over the last few cardiac cycles ----
# Window length (seconds). Captures ~5 cardiac cycles at HR=60-80 bpm.
_PHASE_PORTRAIT_WINDOW_S = 1.0

# (x_id, y_id, x_label, y_label) — the SBML ids whose paired evolution
# traces the phase portrait. Sentinel "__phase__" for x_id triggers the
# degenerate variant where the x axis is cardiac phase (t mod period)
# rather than a state variable; used by the heart-only submodel which
# lacks a volume observable.
_PHASE_PORTRAIT_PAIR = ("__phase__", "E_LV", "Cardiac phase", "LV elastance", "fraction of beat", "mmHg/mL")




def _infer_unit_from_id(name: str) -> str:
    """Best-effort fallback when the SBML doesn't declare a unit on a rateRule
    or assignmentRule variable. Inferred from naming conventions used in the
    Heldt2002 / Koo2013 / Shorten2007 model families. Returns "(unitless)"
    when no convention matches.
    """
    if name.startswith("V_") or name.startswith("Vlv") or name.startswith("Vla") or name.startswith("Vra") or name.startswith("Vrv") or name.startswith("Vao") or name.startswith("Vsv") or name.startswith("Vve") or name.startswith("Vcor"):
        return "mL"
    if name.startswith("F_") or name in ("Faod", "Faop", "Fpad", "Fpap", "COutput"):
        return "mL/s"
    if name.startswith("P_") or name in ("MAP", "Plv", "Pla", "Pra", "Prv", "Pao", "Paopc"):
        return "mmHg"
    if name.startswith("E_") or name in ("Emaxlv", "Emaxla", "Emaxra", "Emaxrv", "Eminlv", "Eminla", "Eminra", "Eminrv"):
        return "mmHg/mL"
    if name.startswith("R_"):
        return "PRU"  # peripheral resistance units (mmHg·s/mL)
    if name.startswith("C_") and len(name) > 2 and name[2:].isalpha():
        return "mL/mmHg"
    if name.startswith("HR") or name == "hrf":
        return "1/min"
    if name.startswith("sub_X_") or name.startswith("conc_X_"):
        return "substance"  # PBPK tracer
    return "(unitless)"




# Lumped Parameter Circulation (Heldt2002 LPC submodel) grouping. The LPC
# model uses lowercase 2-3 letter compartment codes appended directly to
# Vxx / Fxx / Pxx prefixes (e.g. Vlv, Faod, MAP), distinct from the
# circpbpk family's underscore-separated UPPERCASE convention (V_LV, F_AO).
_LPC_GROUP_LOOKUP = {
    # Cardiac chambers
    "Vla": "cardiac_chambers", "Vlv": "cardiac_chambers",
    "Vra": "cardiac_chambers", "Vrv": "cardiac_chambers",
    # Aorta + pulmonary trunk
    "Vaod": "lpc_central_vessels", "Vaop": "lpc_central_vessels",
    "Vpa": "lpc_central_vessels", "Vpad": "lpc_central_vessels", "Vpap": "lpc_central_vessels",
    # Pulmonary perfusion
    "Vpc": "lpc_pulmonary_perfusion", "Vpv": "lpc_pulmonary_perfusion",
    # Systemic perfusion
    "Vsa": "lpc_systemic_perfusion", "Vsap": "lpc_systemic_perfusion",
    "Vsc": "lpc_systemic_perfusion", "Vsv": "lpc_systemic_perfusion",
    "Vvc": "lpc_systemic_perfusion",
    # Coronary perfusion (8 subcompartments)
    "Vcorao": "lpc_coronary_perfusion", "Vcorcap": "lpc_coronary_perfusion",
    "Vcorea": "lpc_coronary_perfusion", "Vcorev": "lpc_coronary_perfusion",
    "Vcorla": "lpc_coronary_perfusion", "Vcorlv": "lpc_coronary_perfusion",
    "Vcorsa": "lpc_coronary_perfusion", "Vcorsv": "lpc_coronary_perfusion",
    # Flows
    "Faod": "lpc_blood_flows", "Faop": "lpc_blood_flows",
    "Fpad": "lpc_blood_flows", "Fpap": "lpc_blood_flows",
    # Pressures
    "MAP": "lpc_blood_pressures", "Paopc": "lpc_blood_pressures",
}

def _humanize_from_compartment_code(name: str) -> Optional[str]:
    """Map a Heldt2002-style compartment-code id to a friendly label.

    Returns None if the id doesn't follow the V_/sub_X_/conc_X_/F_AO/P_*
    convention or the suffix doesn't match a known compartment. Callers are
    expected to fall through to other strategies (SBML name attribute, raw id).
    """
    if name.startswith("sub_X_"):
        compartment = name[len("sub_X_"):]
        readable = _COMPARTMENT_NAMES.get(compartment)
        if readable:
            return f"Tracer amount in {readable}"
        return f"Tracer amount in {compartment}"
    if name.startswith("conc_X_"):
        compartment = name[len("conc_X_"):]
        readable = _COMPARTMENT_NAMES.get(compartment)
        if readable:
            return f"Tracer concentration in {readable}"
        return f"Tracer concentration in {compartment}"
    if name.startswith("V_"):
        compartment = name[2:]
        readable = _COMPARTMENT_NAMES.get(compartment)
        if readable:
            return f"{readable} volume"
    if name.startswith("F_AO"):
        return "Aortic flow"
    if name.startswith("P_") and len(name) > 2:
        compartment = name[2:]
        readable = _COMPARTMENT_NAMES.get(compartment)
        if readable:
            return f"{readable} pressure"
    return None


def _signal_value(signal: BioSignal) -> Any:
    value = getattr(signal, "value", None)
    if isinstance(value, dict) and set(value.keys()) == {"payload"}:
        return value["payload"]
    return value


def _coerce_scalar(value: Any) -> Optional[float]:
    """Pull a float out of various override carrier shapes.

    Accepts plain numbers and {"value": x} / {"payload": x} record-style payloads.
    """
    if isinstance(value, dict):
        for key in ("value", "payload"):
            if key in value:
                value = value[key]
                break
    try:
        return float(value)
    except (TypeError, ValueError):
        return None



def _patch_uninitialised_parameters(xml_text):
    """Repair SBML files whose <parameter> elements lack an initial value.

    BioModels exports occasionally drop the value/initialAssignment for the
    symbolic time parameter (and rarely other parameters). roadrunner refuses
    to load such models. This routine:

      - Adds an assignmentRule binding `name="time"` (or id starting with
        "time"/"t") parameters to the SBML symbolic time symbol.
      - Sets value="0" on any other uninitialised parameter.

    Returns (xml_text, [(param_id, fix), ...]). xml_text is returned unchanged
    when no patches are needed.
    """
    try:
        root = ET.fromstring(xml_text)
    except ET.ParseError:
        return xml_text, []

    if "}" not in root.tag:
        return xml_text, []
    sbml_ns = root.tag.split("}", 1)[0].lstrip("{")
    mathml_ns = "http://www.w3.org/1998/Math/MathML"

    model_el = next((c for c in root if c.tag.endswith("}model")), None)
    if model_el is None:
        return xml_text, []

    def by_local(parent, local_name):
        suffix = "}" + local_name
        return [el for el in parent.iter() if el.tag.endswith(suffix)]

    determined = set()
    for tag in ("assignmentRule", "rateRule"):
        for el in by_local(model_el, tag):
            v = el.attrib.get("variable")
            if v:
                determined.add(v)
    for el in by_local(model_el, "initialAssignment"):
        sym = el.attrib.get("symbol")
        if sym:
            determined.add(sym)

    list_of_rules = next((c for c in model_el if c.tag.endswith("}listOfRules")), None)

    patches = []
    for param_el in by_local(model_el, "parameter"):
        pid = param_el.attrib.get("id")
        if not pid or "value" in param_el.attrib or pid in determined:
            continue
        name_attr = param_el.attrib.get("name", "")
        looks_like_time = (
            name_attr.lower() == "time"
            or pid == "t"
            or pid.lower().startswith("time")
        )
        if looks_like_time:
            if list_of_rules is None:
                list_of_rules = ET.SubElement(model_el, "{" + sbml_ns + "}listOfRules")
            rule = ET.SubElement(list_of_rules, "{" + sbml_ns + "}assignmentRule", {"variable": pid})
            math_el = ET.SubElement(rule, "{" + mathml_ns + "}math")
            csym = ET.SubElement(
                math_el,
                "{" + mathml_ns + "}csymbol",
                {"encoding": "text", "definitionURL": "http://www.sbml.org/sbml/symbols/time"},
            )
            csym.text = "t"
            patches.append((pid, "assignmentRule->symbolic time"))
        else:
            param_el.set("value", "0")
            patches.append((pid, "value=0"))

    if not patches:
        return xml_text, []

    ET.register_namespace("", sbml_ns)
    ET.register_namespace("math", mathml_ns)
    return ET.tostring(root, encoding="unicode"), patches


class Heldt2002OrthostaticstressHeartModel(biosim.BioModule):
    """Tellurium-backed wrapper for Heldt2002 Orthostatic Stress - Heart."""

    def __init__(
        self,
        model_path: str = "data/MODEL1006230103.xml",
        integration_step: float = 0.01,
    ) -> None:
        if integration_step <= 0:
            raise ValueError("integration_step must be positive")
        self.integration_step = float(integration_step)
        self._model_path = Path(__file__).resolve().parent.parent / model_path
        self._runner: Any = None
        # Discover observables and units up-front from the SBML XML so that
        # outputs() returns a stable schema before setup() runs. The platform
        # snapshots the spec early and validates final signal keys against it.
        self._observables, self._observable_units, self._observable_display_names = self._discover_observables_from_xml()
        self._initial_values: Dict[str, float] = {}
        self._history: List[Dict[str, float]] = []
        self._time = 0.0
        self._input_overrides: Dict[str, BioSignal] = {}
        self._outputs: Dict[str, BioSignal] = {}
        self._patches_applied: List[tuple] = []

    # ---- biosim BioModule API ----

    def setup(self, config: Optional[Dict[str, Any]] = None) -> None:
        import tellurium as te

        xml_text = self._model_path.read_text()
        patched_text, self._patches_applied = _patch_uninitialised_parameters(xml_text)
        self._runner = te.loadSBMLModel(patched_text if self._patches_applied else str(self._model_path))
        # Re-discover in case the patched XML grew an assignmentRule that
        # newly converts a parameter into something tellurium tracks.
        observables, units, display_names = self._discover_observables_from_xml()
        if observables:
            self._observables = observables
            self._observable_units = units
            self._observable_display_names = display_names
        self._initial_values = self._read_observables()
        self._time = 0.0
        self._history = [{"t": 0.0, **self._initial_values}]
        self._publish_outputs(0.0)

    def reset(self) -> None:
        if self._runner is not None and hasattr(self._runner, "reset"):
            self._runner.reset()
        self._time = 0.0
        self._history = []
        self._outputs = {}
        if self._runner is not None:
            self._initial_values = self._read_observables()
            self._history = [{"t": 0.0, **self._initial_values}]
            self._publish_outputs(0.0)

    def inputs(self) -> dict[str, SignalSpec]:
        specs: dict[str, SignalSpec] = {
            "integration_step": SignalSpec.scalar(
                dtype="float64",
                accepted_profiles=(
                    AcceptedSignalProfile(
                        signal_type="scalar",
                        dtype="float64",
                        accepted_units=(_TIME_UNIT,),
                        description="Output sampling step for the tellurium simulator.",
                    ),
                    AcceptedSignalProfile(
                        signal_type="record",
                        schema={"payload": "json"},
                        description="Override carrier for the integration step.",
                    ),
                ),
                description="Output sampling step for the tellurium simulator.",
            ),
        }
        for name, (_sbml, _default, units, desc) in _PARAMETER_INPUTS.items():
            specs[name] = SignalSpec.scalar(
                dtype="float64",
                accepted_profiles=(
                    AcceptedSignalProfile(
                        signal_type="scalar",
                        dtype="float64",
                        accepted_units=(units,),
                        description=desc,
                    ),
                    AcceptedSignalProfile(
                        signal_type="record",
                        schema={"payload": "json"},
                        description="Override carrier (record) for " + name + ".",
                    ),
                ),
                description=desc,
            )
        for name, (_targets, _default, units, desc) in _MULTIPLIER_INPUTS.items():
            specs[name] = SignalSpec.scalar(
                dtype="float64",
                accepted_profiles=(
                    AcceptedSignalProfile(
                        signal_type="scalar",
                        dtype="float64",
                        accepted_units=(units,),
                        description=desc,
                    ),
                    AcceptedSignalProfile(
                        signal_type="record",
                        schema={"payload": "json"},
                        description="Override carrier (record) for " + name + ".",
                    ),
                ),
                description=desc,
            )
        return specs

    def set_inputs(self, inputs: Dict[str, BioSignal]) -> None:
        self._input_overrides = dict(inputs or {})
        self._apply_overrides()

    def outputs(self) -> dict[str, SignalSpec]:
        state_schema = {name: "float" for name in self._observables} or {"payload": "json"}
        summary_schema = {
            "duration_simulated": "float",
            "observable_count": "int",
            "largest_change_observable": "str",
            "largest_change_magnitude": "float",
            "peak_observable": "str",
            "peak_value": "float",
        }
        specs: dict[str, SignalSpec] = {
            "state": SignalSpec.record(
                schema=state_schema,
                description=f"Latest value of every observable ({_OBSERVABLE_STRATEGY} variables).",
            ),
            "summary": SignalSpec.record(
                schema=summary_schema,
                description="Final, peak, and minimum value per observable plus simulated duration.",
            ),
        }
        for name, (_src, units, desc) in _HEADLINE_OUTPUTS.items():
            specs[name] = SignalSpec.scalar(
                dtype="float64",
                description=desc + f" Units: {units}.",
            )
        return specs

    def advance_window(self, start: float, end: float, inputs: Optional[Dict[str, BioSignal]] = None) -> None:
        if inputs:
            self.set_inputs(inputs)
        else:
            self._apply_overrides()

        if self._runner is None:
            self.setup()

        t_end = float(end)
        if t_end <= self._time:
            return

        rows = self._simulate_window(self._time, t_end)
        if rows:
            self._history.extend(rows)
            self._time = float(rows[-1]["t"])
        else:
            self._time = t_end
        self._publish_outputs(self._time)

    def get_outputs(self) -> Dict[str, BioSignal]:
        return dict(self._outputs)

    def visualize(self) -> Optional[List["VisualSpec"]]:
        if not self._history or not self._observables:
            return None
        visuals: List["VisualSpec"] = [
            *self._grouped_timeseries_visuals(),
            self._largest_changes_visual(),
            self._what_happened_visual(),
        ]
        portrait = self._phase_portrait_visual()
        if portrait is not None:
            visuals.append(portrait)
        return visuals

    # ---- helpers ----

    def _discover_observables_from_xml(self):
        """Read observable ids, units, and human-readable names from the SBML file.

        Pure-XML inspection so the schema is known before tellurium is even
        imported. Returns ([observable_ids], {id: unit_or_None}, {id: name}).
        The third dict only contains entries where the SBML carries a `name=`
        attribute that differs from the id; an empty dict is returned otherwise.
        """
        try:
            tree = ET.parse(self._model_path)
        except (ET.ParseError, OSError):
            return [], {}, {}
        root = tree.getroot()
        ns = root.tag.split("}")[0].strip("{") if "}" in root.tag else None
        if not ns:
            return [], {}, {}
        suffix_species = "}species"
        suffix_rate = "}rateRule"
        suffix_param = "}parameter"
        observables: List[str] = []
        units: Dict[str, Optional[str]] = {}
        display: Dict[str, str] = {}
        if _OBSERVABLE_STRATEGY == "species":
            for el in root.iter():
                if el.tag.endswith(suffix_species):
                    sid = el.attrib.get("id")
                    sbo = el.attrib.get("sboTerm", "")
                    # SBO:0000291 = "empty set": SBML mass-balance placeholder
                    # used to represent degradation sinks or de-novo synthesis
                    # sources where the actual transport/source isn't modelled.
                    # These have no biological meaning to a lab user.
                    if sid and sid not in _NON_BIOLOGICAL_OBSERVABLES and sbo != "SBO:0000291":
                        observables.append(sid)
                        units[sid] = el.attrib.get("substanceUnits") or el.attrib.get("units")
                        sbml_name = el.attrib.get("name")
                        if sbml_name and sbml_name != sid:
                            display[sid] = sbml_name
        else:
            # rateRule strategy: build an id->name map across <parameter> first,
            # then walk rateRules and look up the name for each rule's variable.
            param_names: Dict[str, str] = {}
            for el in root.iter():
                if el.tag.endswith(suffix_param):
                    pid = el.attrib.get("id")
                    pname = el.attrib.get("name")
                    if pid and pname and pname != pid:
                        param_names[pid] = pname
            for el in root.iter():
                if el.tag.endswith(suffix_rate):
                    var = el.attrib.get("variable")
                    if var and var not in _NON_BIOLOGICAL_OBSERVABLES:
                        observables.append(var)
                        units[var] = None
                        if var in param_names:
                            display[var] = param_names[var]
            # Fallback: if rateRule discovery yielded no biological observables,
            # walk assignmentRule variables instead. Some BioModels submodels
            # (e.g. an isolated heart submodel) carry all their dynamics in
            # assignment rules plus a single placeholder rateRule that the
            # blacklist filtered out.
            if not observables:
                suffix_assign = "}assignmentRule"
                for el in root.iter():
                    if el.tag.endswith(suffix_assign):
                        var = el.attrib.get("variable")
                        if var and var not in _NON_BIOLOGICAL_OBSERVABLES:
                            observables.append(var)
                            units[var] = None
                            if var in param_names:
                                display[var] = param_names[var]
        return observables, units, display

    def _display_name(self, name: str) -> str:
        """User-friendly label for an observable id.

        Resolution order (hand-authored labels OVERRIDE the SBML name= so we
        can give users richer prose than the modeller's terse abbreviation):
          1. Hand-authored model-specific tables (Shorten2007, Koo2013,
             Heldt2002 heart).
          2. SBML <species name="..."> or <parameter name="..."> if it
             differs from the id (covers any unmapped Koo2013 species etc.).
          3. Heldt2002 compartment-code pattern (`V_LV` -> `Left Ventricle volume`).
          4. The raw id, unchanged.
        """
        # Lift the SBML name= attribute (if any) so we can look up hand
        # labels by either the raw id (e.g. `vS`) or the SBML-given name
        # (e.g. `s1` -> `Ca_ex`).
        bio_key = self._observable_display_names.get(name, name)
        for table in (_SHORTEN2007_LABELS, _KOO2013_LABELS, _HELDT2002_LABELS):
            if bio_key in table:
                return table[bio_key]
            if name in table:
                return table[name]
        # No hand label: prefer the SBML name= attribute over the raw id.
        if bio_key != name:
            return bio_key
        compartment_label = _humanize_from_compartment_code(name)
        if compartment_label:
            return compartment_label
        return name

    def _read_observables(self) -> Dict[str, float]:
        values: Dict[str, float] = {}
        for name in self._observables:
            try:
                values[name] = float(self._runner[name])
            except (KeyError, ValueError, TypeError, RuntimeError):
                values[name] = 0.0
        return values

    def _simulate_window(self, start: float, end: float) -> List[Dict[str, float]]:
        if not self._observables:
            return []
        n_steps = max(2, int(math.ceil((end - start) / self.integration_step)) + 1)
        selections = ["time", *self._observables]
        result = self._runner.simulate(start, end, n_steps, selections=selections)
        rows: List[Dict[str, float]] = []
        for i in range(result.shape[0]):
            t = float(result[i, 0])
            if rows and abs(t - rows[-1]["t"]) < 1e-12:
                continue
            if self._history and i == 0 and abs(t - self._history[-1]["t"]) < 1e-12:
                continue
            row = {"t": t}
            for j, name in enumerate(self._observables, start=1):
                row[name] = float(result[i, j])
            rows.append(row)
        return rows

    def _publish_outputs(self, t: float) -> None:
        latest = self._history[-1]
        state_payload = {name: latest.get(name, 0.0) for name in self._observables}
        summary_payload = self._compute_summary(t)
        source = getattr(self, "_world_name", self.__class__.__name__)
        all_specs = self.outputs()
        outs: Dict[str, BioSignal] = {
            "state": RecordSignal(source=source, name="state", value=state_payload, emitted_at=float(t), spec=all_specs["state"]),
            "summary": RecordSignal(source=source, name="summary", value=summary_payload, emitted_at=float(t), spec=all_specs["summary"]),
        }
        for out_name, (src_id, _units, _desc) in _HEADLINE_OUTPUTS.items():
            # Time-windowed mean over the last _HEADLINE_WINDOW_S seconds, so
            # waveform-style observables (cardiac pressure, elastance) report
            # a stable cycle-averaged value rather than a phase-aliased snapshot.
            window_start = float(t) - _HEADLINE_WINDOW_S
            window_values = [
                row[src_id] for row in self._history
                if src_id in row and float(row.get("t", 0.0)) >= window_start
            ]
            if window_values:
                value = sum(window_values) / len(window_values)
            elif self._runner is not None:
                try:
                    value = float(self._runner[src_id])
                except (KeyError, ValueError, TypeError, RuntimeError):
                    value = 0.0
            else:
                value = float(latest.get(src_id, 0.0))
            outs[out_name] = ScalarSignal(
                source=source, name=out_name, value=float(value),
                emitted_at=float(t), spec=all_specs[out_name],
            )
        self._outputs = outs

    def _compute_summary(self, t: float) -> Dict[str, Any]:
        if not self._observables or len(self._history) < 2:
            return {
                "duration_simulated": float(t),
                "observable_count": len(self._observables),
                "largest_change_observable": "",
                "largest_change_magnitude": 0.0,
                "peak_observable": "",
                "peak_value": 0.0,
            }
        first = self._history[0]
        last = self._history[-1]
        changes = {name: abs(last.get(name, 0.0) - first.get(name, 0.0)) for name in self._observables}
        biggest_change = max(changes, key=changes.get)
        peaks = {name: max(point.get(name, 0.0) for point in self._history) for name in self._observables}
        biggest_peak = max(peaks, key=peaks.get)
        return {
            "duration_simulated": float(t),
            "observable_count": len(self._observables),
            "largest_change_observable": biggest_change,
            "largest_change_magnitude": float(changes[biggest_change]),
            "peak_observable": biggest_peak,
            "peak_value": float(peaks[biggest_peak]),
        }

    def _apply_overrides(self) -> None:
        # 1. integration_step (always present)
        signal = self._input_overrides.get("integration_step")
        if signal is not None:
            number = _coerce_scalar(_signal_value(signal))
            if number is not None and number > 0:
                self.integration_step = number
        if self._runner is None:
            return
        # 2. direct parameter inputs
        for input_name, (sbml_id, _default, _units, _desc) in _PARAMETER_INPUTS.items():
            sig = self._input_overrides.get(input_name)
            if sig is None:
                continue
            number = _coerce_scalar(_signal_value(sig))
            if number is None:
                continue
            try:
                self._runner[sbml_id] = float(number)
            except (KeyError, ValueError, TypeError, RuntimeError):
                pass
        # 3. multiplier inputs: scale each baseline parameter
        for input_name, (sbml_ids, _default, _units, _desc) in _MULTIPLIER_INPUTS.items():
            sig = self._input_overrides.get(input_name)
            if sig is None:
                continue
            number = _coerce_scalar(_signal_value(sig))
            if number is None:
                continue
            for sbml_id in sbml_ids:
                base = self._param_baselines.get(sbml_id)
                if base is None:
                    continue
                try:
                    self._runner[sbml_id] = float(base) * float(number)
                except (KeyError, ValueError, TypeError, RuntimeError):
                    pass

    def _phase_portrait_visual(self) -> Optional["VisualSpec"]:
        """Parametric phase portrait: x vs y over the last
        ``_PHASE_PORTRAIT_WINDOW_S`` seconds. PV loop for circpbpk / lpc;
        elastance vs cardiac phase for the isolated heart submodel.
        Emitted with render="scatter" — the existing canvas scatter
        renderer is the simplest target. If the renderer cannot connect
        points, switch this to a dedicated "phase_portrait" render type.
        """
        if _PHASE_PORTRAIT_PAIR is None or not self._history:
            return None
        x_id, y_id, x_label, y_label, x_unit, y_unit = _PHASE_PORTRAIT_PAIR
        t_now = float(self._history[-1].get("t", 0.0))
        # Adaptive window: one cardiac cycle plus a 5% margin. This captures
        # exactly one PV loop at the current heart rate, avoiding the multi-
        # cycle "fuzzy band" you get with a fixed window. Falls back to
        # _PHASE_PORTRAIT_WINDOW_S (1.0 s) if HR is unreadable.
        try:
            hr_now = float(self._runner["HR"]) if self._runner is not None else 60.0
        except (KeyError, ValueError, TypeError, RuntimeError):
            hr_now = 60.0
        cycle_window = (60.0 / max(hr_now, 1.0)) * 1.05
        window_s = max(cycle_window, _PHASE_PORTRAIT_WINDOW_S)
        t_start = t_now - window_s
        window = [r for r in self._history if float(r.get("t", 0.0)) >= t_start]
        if len(window) < 2:
            return None
        points: List[Dict[str, Any]] = []
        if x_id == "__phase__":
            try:
                hr_bpm = float(self._runner["HR"]) if self._runner is not None else 60.0
            except (KeyError, ValueError, TypeError, RuntimeError):
                hr_bpm = 60.0
            period = 60.0 / max(hr_bpm, 1.0)
            for r in window:
                t = float(r.get("t", 0.0))
                y_val = r.get(y_id)
                if y_val is None and self._runner is not None:
                    try: y_val = float(self._runner[y_id])
                    except (KeyError, ValueError, TypeError, RuntimeError): y_val = 0.0
                points.append({"x": (t % period) / period, "y": float(y_val or 0.0), "series": "elastance"})
            description = (
                f"LV elastance over the cardiac phase, sampled across the last "
                f"{_PHASE_PORTRAIT_WINDOW_S:g} s of simulation. The elastance function "
                f"shape encodes systolic timing and contractile strength."
            )
            title = "LV elastance phase portrait"
        else:
            for r in window:
                x_val = r.get(x_id)
                y_val = r.get(y_id)
                if x_val is None or y_val is None:
                    continue
                points.append({"x": float(x_val), "y": float(y_val), "series": "LV cycle"})
            description = (
                f"Pressure-volume loop over the last {_PHASE_PORTRAIT_WINDOW_S:g} s of "
                f"simulation. Each cardiac cycle traces a closed loop; loop area encodes "
                f"stroke work, x-extent encodes preload, and the upper plateau encodes "
                f"afterload."
            )
            title = "LV pressure-volume loop"
        if not points:
            return None
        return {
            "render": "scatter",
            "description": description,
            "data": {
                "title": title,
                "x_label": x_label,
                "y_label": y_label,
                "x_unit": x_unit,
                "y_unit": y_unit,
                "connect_points": True,
                "points": points,
            },
        }

    def _grouped_timeseries_visuals(self) -> List["VisualSpec"]:
        groups: Dict[str, List[str]] = {}
        for name in self._observables:
            display = self._observable_display_names.get(name)
            groups.setdefault(_group_observable(name, display), []).append(name)
        visuals: List["VisualSpec"] = []
        for key, (title_suffix, description) in _GROUP_META.items():
            names = groups.get(key)
            if not names:
                continue
            visuals.append({
                "render": "timeseries",
                "description": description,
                "data": {
                    "title": f"{_TITLE} - {title_suffix}",
                    "x_unit": _TIME_UNIT,
                    "series": [
                        {
                            "name": self._display_name(name),
                            "points": [[point["t"], point[name]] for point in self._history],
                        }
                        for name in names
                    ],
                },
            })
        return visuals

    def _largest_changes_visual(self) -> "VisualSpec":
        if len(self._history) < 2:
            ranges = {name: 0.0 for name in self._observables}
        else:
            ranges = {}
            for name in self._observables:
                values = [point.get(name, 0.0) for point in self._history]
                ranges[name] = max(values) - min(values)
        ranked = sorted(ranges.items(), key=lambda pair: pair[1], reverse=True)[:8]
        return {
            "render": "bar",
            "description": "Which observables shifted the most during the run?",
            "data": {
                "title": f"{_TITLE} - largest excursions during the run",
                "categories": [self._display_name(name) for name, _ in ranked],
                "values": [value for _, value in ranked],
            },
        }

    def _what_happened_visual(self) -> "VisualSpec":
        first = self._history[0]
        last = self._history[-1]
        duration = last["t"] - first["t"]
        changes = {name: last.get(name, 0.0) - first.get(name, 0.0) for name in self._observables}
        biggest_change_name = max(changes, key=lambda n: abs(changes[n]))
        peaks = {name: max(point.get(name, 0.0) for point in self._history) for name in self._observables}
        biggest_peak_name = max(peaks, key=peaks.get)
        steady = self._steady_state_assessment()
        unit = self._observable_units.get(biggest_peak_name) or _infer_unit_from_id(biggest_peak_name)
        rows = [
            ["What did this run track?", f"{len(self._observables)} {_OBSERVABLE_STRATEGY} observables in the {_TITLE} SBML model"],
            ["How long did it run?", f"{duration:.3g} {_TIME_UNIT}"],
            ["Which observable changed the most?", f"{self._display_name(biggest_change_name)} ({changes[biggest_change_name]:+.3g})"],
            ["Largest peak?", f"{self._display_name(biggest_peak_name)} at {peaks[biggest_peak_name]:.3g} {unit}"],
            ["Did anything reach steady state?", steady],
        ]
        return {
            "render": "table",
            "description": "What did this simulation actually show, in plain language?",
            "data": {
                "title": "What Happened",
                "columns": ["Question", "Answer"],
                "rows": rows,
            },
        }

    def _steady_state_assessment(self) -> str:
        if len(self._history) < 10:
            return "Not enough samples to assess."
        tail_count = max(2, len(self._history) // 10)
        tail = self._history[-tail_count:]
        steady = []
        for name in self._observables:
            values = [point.get(name, 0.0) for point in tail]
            v_min, v_max = min(values), max(values)
            scale = max(abs(v_min), abs(v_max), 1e-12)
            if (v_max - v_min) / scale < 0.01:
                steady.append(name)
        if not steady:
            return "No observable settled within 1% over the last 10% of the run."
        if len(steady) == len(self._observables):
            return "All observables flattened within 1% over the last 10% of the run."
        return f"{len(steady)} of {len(self._observables)} observables settled within 1% over the last 10% of the run."
