# Generated by scripts/refactor_labs.py - safe to edit
"""Tests for the Heldt2002 Orthostatic Stress - Circulation PBPK wrapper."""
from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest
import yaml


_MODEL_DIR = Path(__file__).resolve().parents[1]
_MANIFEST_PATH = _MODEL_DIR / "model.yaml"
_WRAPPER_PATH = _MODEL_DIR / "src" / "heldt2002_orthostaticstress_circpbpk.py"


def _find_bsim_src(start: Path) -> Path | None:
    for parent in [start, *start.parents]:
        for candidate in (parent / "biosim" / "src", parent / "bsim-active" / "biosim" / "src"):
            if (candidate / "biosim").is_dir():
                return candidate
    return None


def _load_wrapper():
    bsim_src = _find_bsim_src(_MODEL_DIR)
    if bsim_src is not None and str(bsim_src) not in sys.path:
        sys.path.insert(0, str(bsim_src))
    # Load by file path so labs that share the package name `src` do not
    # collide in sys.modules when pytest collects them all in one session.
    unique_name = f"heldt2002_orthostaticstress_circpbpk__lab_module"
    spec = importlib.util.spec_from_file_location(unique_name, _WRAPPER_PATH)
    module = importlib.util.module_from_spec(spec)
    sys.modules[unique_name] = module
    spec.loader.exec_module(module)
    return module


_wrapper = _load_wrapper()
Heldt2002OrthostaticstressCircpbpkModel = _wrapper.Heldt2002OrthostaticstressCircpbpkModel


def _advance_or_skip(module, start: float, end: float) -> None:
    try:
        module.advance_window(start, end)
    except (ImportError, ModuleNotFoundError) as exc:
        pytest.skip(f"Optional runtime dependency missing: {exc}")


def test_instantiation():
    module = Heldt2002OrthostaticstressCircpbpkModel()
    assert module.integration_step > 0
    assert isinstance(module.inputs(), dict)
    assert "integration_step" in module.inputs()
    assert {"state", "summary"}.issubset(set(module.outputs().keys()))


def test_advance_accumulates_history():
    module = Heldt2002OrthostaticstressCircpbpkModel()
    _advance_or_skip(module, 0.0, 60.0)
    assert len(module._history) > 1, "advance_window must accumulate trajectory points"
    assert module._observables, "observables must be discovered after setup"
    assert {"state", "summary"}.issubset(set(module.get_outputs().keys()))


def test_model_yaml_io_matches_module():
    manifest = yaml.safe_load(_MANIFEST_PATH.read_text())
    declared_inputs = {entry["name"] for entry in manifest["io"]["inputs"]}
    declared_outputs = {entry["name"] for entry in manifest["io"]["outputs"]}
    module = Heldt2002OrthostaticstressCircpbpkModel()
    assert declared_inputs == set(module.inputs().keys())
    assert declared_outputs == set(module.outputs().keys())
