# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Koo2013 Shear-Stress Induced NO Production.

Source: biomodels_ebi:BIOMD0000000467
Original: https://www.ebi.ac.uk/biomodels/BIOMD0000000467
"""
from __future__ import annotations

from typing import Any

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Koo2013ShearStressNoProductionModel(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Koo2013 Shear-Stress Induced NO Production."""

    _OBSERVABLE_STRATEGY = 'species'
    _NON_BIOLOGICAL_OBSERVABLES = {'dummy'}
    _TIME_UNIT = 's'
    _SBML_ID = 'BIOMD0000000467'
    _TITLE = 'Koo2013 Shear-Stress Induced NO Production'
    _PARAMETER_INPUTS = {'cytosolic_calcium': ('s3',
                       117.2,
                       'substance',
                       'Cytosolic Ca2+ concentration. This submodel treats Ca2+ as an external '
                       'input (boundaryCondition=true in the SBML); compose with '
                       'koo2013-calcium-influx for realistic dynamics.')}
    _MULTIPLIER_INPUTS = {}
    _HEADLINE_OUTPUTS = {'active_eNOS': ('s45',
                 'substance',
                 'Active eNOS-CaM-Ca4 complex. Catalyses NO production from L-arginine.'),
 'nitric_oxide': ('s64',
                  'substance',
                  "Nitric oxide (NO) amount. The model's primary downstream readout.")}
    _HEADLINE_WINDOW_S = 60.0
    _HEADLINE_EMIT_UNITS = True

    def __init__(
        self,
        model_path: str = 'data/BIOMD0000000467.xml',
        integration_step: float = 1.0,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
