# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Heldt2002 Orthostatic Stress - Heart.

Source: biomodels_ebi:MODEL1006230103
Original: https://www.ebi.ac.uk/biomodels/MODEL1006230103
"""
from __future__ import annotations

import math
import xml.etree.ElementTree as ET
from pathlib import Path
from typing import Any, Dict, List, Optional

import biosim
from biosim.signals import (
    AcceptedSignalProfile,
    BioSignal,
    RecordSignal,
    ScalarSignal,
    SignalSpec,
)


_OBSERVABLE_STRATEGY = "rateRule"

# BioModels exports occasionally carry placeholder parameters with no
# biological meaning (e.g. a `dummy` rate-rule variable left over from the
# curator's scratch work). They survive into the SBML and would otherwise
# show up in the lab's outputs and visualizations as noise. Names listed
# here are silently dropped during observable discovery.
_NON_BIOLOGICAL_OBSERVABLES = {"dummy"}

_TIME_UNIT = "s"
_SBML_ID = "MODEL1006230103"
_TITLE = "Heldt2002 Orthostatic Stress - Heart"


# ---- Lab-specific physiological inputs and outputs ----
_PARAMETER_INPUTS = {
    'heart_rate': ('HR', 70.0, '1/min', 'Heart rate (beats per minute). Sets the cardiac pacing frequency.'),
    'systolic_elastance': ('Esys', 5.6, 'mmHg/mL', 'Peak systolic LV elastance. Higher values = stronger contractility.'),
    'diastolic_elastance': ('Edia', 0.19, 'mmHg/mL', 'Diastolic LV elastance. Sets the chamber compliance during filling.'),
}
_MULTIPLIER_INPUTS = {
}
_HEADLINE_OUTPUTS = {
    'elastance': ('E_LV', 'mmHg/mL', 'Time-varying left ventricle elastance. The headline output of the contractility model.'),
}

# Time window (in seconds) over which headline scalars are averaged.
# Smooths waveform-style observables; harmless for slow signals.
_HEADLINE_WINDOW_S = 2.0


def _signal_value(signal: BioSignal) -> Any:
    value = getattr(signal, "value", None)
    if isinstance(value, dict) and set(value.keys()) == {"payload"}:
        return value["payload"]
    return value


def _coerce_scalar(value: Any) -> Optional[float]:
    """Pull a float out of various override carrier shapes.

    Accepts plain numbers and {"value": x} / {"payload": x} record-style payloads.
    """
    if isinstance(value, dict):
        for key in ("value", "payload"):
            if key in value:
                value = value[key]
                break
    try:
        return float(value)
    except (TypeError, ValueError):
        return None



def _patch_uninitialised_parameters(xml_text):
    """Repair SBML files whose <parameter> elements lack an initial value.

    BioModels exports occasionally drop the value/initialAssignment for the
    symbolic time parameter (and rarely other parameters). roadrunner refuses
    to load such models. This routine:

      - Adds an assignmentRule binding `name="time"` (or id starting with
        "time"/"t") parameters to the SBML symbolic time symbol.
      - Sets value="0" on any other uninitialised parameter.

    Returns (xml_text, [(param_id, fix), ...]). xml_text is returned unchanged
    when no patches are needed.
    """
    try:
        root = ET.fromstring(xml_text)
    except ET.ParseError:
        return xml_text, []

    if "}" not in root.tag:
        return xml_text, []
    sbml_ns = root.tag.split("}", 1)[0].lstrip("{")
    mathml_ns = "http://www.w3.org/1998/Math/MathML"

    model_el = next((c for c in root if c.tag.endswith("}model")), None)
    if model_el is None:
        return xml_text, []

    def by_local(parent, local_name):
        suffix = "}" + local_name
        return [el for el in parent.iter() if el.tag.endswith(suffix)]

    determined = set()
    for tag in ("assignmentRule", "rateRule"):
        for el in by_local(model_el, tag):
            v = el.attrib.get("variable")
            if v:
                determined.add(v)
    for el in by_local(model_el, "initialAssignment"):
        sym = el.attrib.get("symbol")
        if sym:
            determined.add(sym)

    list_of_rules = next((c for c in model_el if c.tag.endswith("}listOfRules")), None)

    patches = []
    for param_el in by_local(model_el, "parameter"):
        pid = param_el.attrib.get("id")
        if not pid or "value" in param_el.attrib or pid in determined:
            continue
        name_attr = param_el.attrib.get("name", "")
        looks_like_time = (
            name_attr.lower() == "time"
            or pid == "t"
            or pid.lower().startswith("time")
        )
        if looks_like_time:
            if list_of_rules is None:
                list_of_rules = ET.SubElement(model_el, "{" + sbml_ns + "}listOfRules")
            rule = ET.SubElement(list_of_rules, "{" + sbml_ns + "}assignmentRule", {"variable": pid})
            math_el = ET.SubElement(rule, "{" + mathml_ns + "}math")
            csym = ET.SubElement(
                math_el,
                "{" + mathml_ns + "}csymbol",
                {"encoding": "text", "definitionURL": "http://www.sbml.org/sbml/symbols/time"},
            )
            csym.text = "t"
            patches.append((pid, "assignmentRule->symbolic time"))
        else:
            param_el.set("value", "0")
            patches.append((pid, "value=0"))

    if not patches:
        return xml_text, []

    ET.register_namespace("", sbml_ns)
    ET.register_namespace("math", mathml_ns)
    return ET.tostring(root, encoding="unicode"), patches


class Heldt2002OrthostaticstressHeartModel(biosim.BioModule):
    """Tellurium-backed wrapper for Heldt2002 Orthostatic Stress - Heart."""

    def __init__(
        self,
        model_path: str = "data/MODEL1006230103.xml",
        integration_step: float = 0.01,
    ) -> None:
        if integration_step <= 0:
            raise ValueError("integration_step must be positive")
        self.integration_step = float(integration_step)
        self._model_path = Path(__file__).resolve().parent.parent / model_path
        self._runner: Any = None
        # Discover observables and units up-front from the SBML XML so that
        # outputs() returns a stable schema before setup() runs. The platform
        # snapshots the spec early and validates final signal keys against it.
        self._observables, _, _ = self._discover_observables_from_xml()
        self._initial_values: Dict[str, float] = {}
        self._history: List[Dict[str, float]] = []
        self._time = 0.0
        self._input_overrides: Dict[str, BioSignal] = {}
        self._outputs: Dict[str, BioSignal] = {}
        self._patches_applied: List[tuple] = []

    # ---- biosim BioModule API ----

    def setup(self, config: Optional[Dict[str, Any]] = None) -> None:
        import tellurium as te

        xml_text = self._model_path.read_text()
        patched_text, self._patches_applied = _patch_uninitialised_parameters(xml_text)
        self._runner = te.loadSBMLModel(patched_text if self._patches_applied else str(self._model_path))
        # Re-discover in case the patched XML grew an assignmentRule that
        # newly converts a parameter into something tellurium tracks.
        observables, _, _ = self._discover_observables_from_xml()
        if observables:
            self._observables = observables
        self._initial_values = self._read_observables()
        self._time = 0.0
        self._history = [{"t": 0.0, **self._initial_values}]
        self._publish_outputs(0.0)

    def reset(self) -> None:
        if self._runner is not None and hasattr(self._runner, "reset"):
            self._runner.reset()
        self._time = 0.0
        self._history = []
        self._outputs = {}
        if self._runner is not None:
            self._initial_values = self._read_observables()
            self._history = [{"t": 0.0, **self._initial_values}]
            self._publish_outputs(0.0)

    def inputs(self) -> dict[str, SignalSpec]:
        specs: dict[str, SignalSpec] = {
            "integration_step": SignalSpec.scalar(
                dtype="float64",
                accepted_profiles=(
                    AcceptedSignalProfile(
                        signal_type="scalar",
                        dtype="float64",
                        accepted_units=(_TIME_UNIT,),
                        description="Output sampling step for the tellurium simulator.",
                    ),
                    AcceptedSignalProfile(
                        signal_type="record",
                        schema={"payload": "json"},
                        description="Override carrier for the integration step.",
                    ),
                ),
                description="Output sampling step for the tellurium simulator.",
            ),
        }
        for name, (_sbml, _default, units, desc) in _PARAMETER_INPUTS.items():
            specs[name] = SignalSpec.scalar(
                dtype="float64",
                accepted_profiles=(
                    AcceptedSignalProfile(
                        signal_type="scalar",
                        dtype="float64",
                        accepted_units=(units,),
                        description=desc,
                    ),
                    AcceptedSignalProfile(
                        signal_type="record",
                        schema={"payload": "json"},
                        description="Override carrier (record) for " + name + ".",
                    ),
                ),
                description=desc,
            )
        for name, (_targets, _default, units, desc) in _MULTIPLIER_INPUTS.items():
            specs[name] = SignalSpec.scalar(
                dtype="float64",
                accepted_profiles=(
                    AcceptedSignalProfile(
                        signal_type="scalar",
                        dtype="float64",
                        accepted_units=(units,),
                        description=desc,
                    ),
                    AcceptedSignalProfile(
                        signal_type="record",
                        schema={"payload": "json"},
                        description="Override carrier (record) for " + name + ".",
                    ),
                ),
                description=desc,
            )
        return specs

    def set_inputs(self, inputs: Dict[str, BioSignal]) -> None:
        self._input_overrides = dict(inputs or {})
        self._apply_overrides()

    def outputs(self) -> dict[str, SignalSpec]:
        state_schema = {name: "float" for name in self._observables} or {"payload": "json"}
        summary_schema = {
            "duration_simulated": "float",
            "observable_count": "int",
            "largest_change_observable": "str",
            "largest_change_magnitude": "float",
            "peak_observable": "str",
            "peak_value": "float",
        }
        specs: dict[str, SignalSpec] = {
            "state": SignalSpec.record(
                schema=state_schema,
                description=f"Latest value of every observable ({_OBSERVABLE_STRATEGY} variables).",
            ),
            "summary": SignalSpec.record(
                schema=summary_schema,
                description="Final, peak, and minimum value per observable plus simulated duration.",
            ),
            "visualisation_aux": SignalSpec.record(
                schema={
                    "phase_x": "float",
                    "phase_y": "float",
                    "heart_rate_bpm": "float",
                },
                description="Internal phase-portrait payload for the dedicated visualisation model.",
            ),
        }
        for name, (_src, units, desc) in _HEADLINE_OUTPUTS.items():
            specs[name] = SignalSpec.scalar(
                dtype="float64",
                description=desc + f" Units: {units}.",
            )
        return specs

    def advance_window(self, start: float, end: float, inputs: Optional[Dict[str, BioSignal]] = None) -> None:
        if inputs:
            self.set_inputs(inputs)
        else:
            self._apply_overrides()

        if self._runner is None:
            self.setup()

        t_end = float(end)
        if t_end <= self._time:
            return

        rows = self._simulate_window(self._time, t_end)
        if rows:
            self._history.extend(rows)
            self._time = float(rows[-1]["t"])
        else:
            self._time = t_end
        self._publish_outputs(self._time)

    def get_outputs(self) -> Dict[str, BioSignal]:
        return dict(self._outputs)

    # ---- helpers ----

    def _discover_observables_from_xml(self):
        """Read observable ids, units, and human-readable names from the SBML file.

        Pure-XML inspection so the schema is known before tellurium is even
        imported. Returns ([observable_ids], {id: unit_or_None}, {id: name}).
        The third dict only contains entries where the SBML carries a `name=`
        attribute that differs from the id; an empty dict is returned otherwise.
        """
        try:
            tree = ET.parse(self._model_path)
        except (ET.ParseError, OSError):
            return [], {}, {}
        root = tree.getroot()
        ns = root.tag.split("}")[0].strip("{") if "}" in root.tag else None
        if not ns:
            return [], {}, {}
        suffix_species = "}species"
        suffix_rate = "}rateRule"
        suffix_param = "}parameter"
        observables: List[str] = []
        units: Dict[str, Optional[str]] = {}
        display: Dict[str, str] = {}
        if _OBSERVABLE_STRATEGY == "species":
            for el in root.iter():
                if el.tag.endswith(suffix_species):
                    sid = el.attrib.get("id")
                    sbo = el.attrib.get("sboTerm", "")
                    # SBO:0000291 = "empty set": SBML mass-balance placeholder
                    # used to represent degradation sinks or de-novo synthesis
                    # sources where the actual transport/source isn't modelled.
                    # These have no biological meaning to a lab user.
                    if sid and sid not in _NON_BIOLOGICAL_OBSERVABLES and sbo != "SBO:0000291":
                        observables.append(sid)
                        units[sid] = el.attrib.get("substanceUnits") or el.attrib.get("units")
                        sbml_name = el.attrib.get("name")
                        if sbml_name and sbml_name != sid:
                            display[sid] = sbml_name
        else:
            # rateRule strategy: build an id->name map across <parameter> first,
            # then walk rateRules and look up the name for each rule's variable.
            param_names: Dict[str, str] = {}
            for el in root.iter():
                if el.tag.endswith(suffix_param):
                    pid = el.attrib.get("id")
                    pname = el.attrib.get("name")
                    if pid and pname and pname != pid:
                        param_names[pid] = pname
            for el in root.iter():
                if el.tag.endswith(suffix_rate):
                    var = el.attrib.get("variable")
                    if var and var not in _NON_BIOLOGICAL_OBSERVABLES:
                        observables.append(var)
                        units[var] = None
                        if var in param_names:
                            display[var] = param_names[var]
            # Fallback: if rateRule discovery yielded no biological observables,
            # walk assignmentRule variables instead. Some BioModels submodels
            # (e.g. an isolated heart submodel) carry all their dynamics in
            # assignment rules plus a single placeholder rateRule that the
            # blacklist filtered out.
            if not observables:
                suffix_assign = "}assignmentRule"
                for el in root.iter():
                    if el.tag.endswith(suffix_assign):
                        var = el.attrib.get("variable")
                        if var and var not in _NON_BIOLOGICAL_OBSERVABLES:
                            observables.append(var)
                            units[var] = None
                            if var in param_names:
                                display[var] = param_names[var]
        return observables, units, display

    def _read_observables(self) -> Dict[str, float]:
        values: Dict[str, float] = {}
        for name in self._observables:
            try:
                values[name] = float(self._runner[name])
            except (KeyError, ValueError, TypeError, RuntimeError):
                values[name] = 0.0
        return values

    def _simulate_window(self, start: float, end: float) -> List[Dict[str, float]]:
        if not self._observables:
            return []
        n_steps = max(2, int(math.ceil((end - start) / self.integration_step)) + 1)
        selections = ["time", *self._observables]
        result = self._runner.simulate(start, end, n_steps, selections=selections)
        rows: List[Dict[str, float]] = []
        for i in range(result.shape[0]):
            t = float(result[i, 0])
            if rows and abs(t - rows[-1]["t"]) < 1e-12:
                continue
            if self._history and i == 0 and abs(t - self._history[-1]["t"]) < 1e-12:
                continue
            row = {"t": t}
            for j, name in enumerate(self._observables, start=1):
                row[name] = float(result[i, j])
            rows.append(row)
        return rows

    def _publish_outputs(self, t: float) -> None:
        latest = self._history[-1]
        state_payload = {name: latest.get(name, 0.0) for name in self._observables}
        summary_payload = self._compute_summary(t)
        source = getattr(self, "_world_name", self.__class__.__name__)
        all_specs = self.outputs()
        outs: Dict[str, BioSignal] = {
            "state": RecordSignal(source=source, name="state", value=state_payload, emitted_at=float(t), spec=all_specs["state"]),
            "summary": RecordSignal(source=source, name="summary", value=summary_payload, emitted_at=float(t), spec=all_specs["summary"]),
        }
        heart_rate_bpm = 60.0
        if self._runner is not None:
            try:
                heart_rate_bpm = float(self._runner["HR"])
            except (KeyError, ValueError, TypeError, RuntimeError):
                try:
                    heart_rate_bpm = float(self._runner["hrf"]) * 60.0
                except (KeyError, ValueError, TypeError, RuntimeError):
                    heart_rate_bpm = 60.0
        period = 60.0 / max(heart_rate_bpm, 1.0)
        outs["visualisation_aux"] = RecordSignal(
            source=source,
            name="visualisation_aux",
            value={
                "phase_x": (float(t) % period) / period,
                "phase_y": float(latest.get("E_LV", 0.0)),
                "heart_rate_bpm": float(heart_rate_bpm),
            },
            emitted_at=float(t),
            spec=all_specs["visualisation_aux"],
        )
        for out_name, (src_id, _units, _desc) in _HEADLINE_OUTPUTS.items():
            # Time-windowed mean over the last _HEADLINE_WINDOW_S seconds, so
            # waveform-style observables (cardiac pressure, elastance) report
            # a stable cycle-averaged value rather than a phase-aliased snapshot.
            window_start = float(t) - _HEADLINE_WINDOW_S
            window_values = [
                row[src_id] for row in self._history
                if src_id in row and float(row.get("t", 0.0)) >= window_start
            ]
            if window_values:
                value = sum(window_values) / len(window_values)
            elif self._runner is not None:
                try:
                    value = float(self._runner[src_id])
                except (KeyError, ValueError, TypeError, RuntimeError):
                    value = 0.0
            else:
                value = float(latest.get(src_id, 0.0))
            outs[out_name] = ScalarSignal(
                source=source, name=out_name, value=float(value),
                emitted_at=float(t), spec=all_specs[out_name],
            )
        self._outputs = outs

    def _compute_summary(self, t: float) -> Dict[str, Any]:
        if not self._observables or len(self._history) < 2:
            return {
                "duration_simulated": float(t),
                "observable_count": len(self._observables),
                "largest_change_observable": "",
                "largest_change_magnitude": 0.0,
                "peak_observable": "",
                "peak_value": 0.0,
            }
        first = self._history[0]
        last = self._history[-1]
        changes = {name: abs(last.get(name, 0.0) - first.get(name, 0.0)) for name in self._observables}
        biggest_change = max(changes, key=changes.get)
        peaks = {name: max(point.get(name, 0.0) for point in self._history) for name in self._observables}
        biggest_peak = max(peaks, key=peaks.get)
        return {
            "duration_simulated": float(t),
            "observable_count": len(self._observables),
            "largest_change_observable": biggest_change,
            "largest_change_magnitude": float(changes[biggest_change]),
            "peak_observable": biggest_peak,
            "peak_value": float(peaks[biggest_peak]),
        }

    def _apply_overrides(self) -> None:
        # 1. integration_step (always present)
        signal = self._input_overrides.get("integration_step")
        if signal is not None:
            number = _coerce_scalar(_signal_value(signal))
            if number is not None and number > 0:
                self.integration_step = number
        if self._runner is None:
            return
        # 2. direct parameter inputs
        for input_name, (sbml_id, _default, _units, _desc) in _PARAMETER_INPUTS.items():
            sig = self._input_overrides.get(input_name)
            if sig is None:
                continue
            number = _coerce_scalar(_signal_value(sig))
            if number is None:
                continue
            try:
                self._runner[sbml_id] = float(number)
            except (KeyError, ValueError, TypeError, RuntimeError):
                pass
        # 3. multiplier inputs: scale each baseline parameter
        for input_name, (sbml_ids, _default, _units, _desc) in _MULTIPLIER_INPUTS.items():
            sig = self._input_overrides.get(input_name)
            if sig is None:
                continue
            number = _coerce_scalar(_signal_value(sig))
            if number is None:
                continue
            for sbml_id in sbml_ids:
                base = self._param_baselines.get(sbml_id)
                if base is None:
                    continue
                try:
                    self._runner[sbml_id] = float(base) * float(number)
                except (KeyError, ValueError, TypeError, RuntimeError):
                    pass
