# Generated by scripts/refactor_labs.py - safe to edit
# SPDX-FileCopyrightText: 2026-present Biosimulant Team
# SPDX-License-Identifier: MIT
"""Tellurium-backed wrapper for Heldt2002 Orthostatic Stress - Heart.

Source: biomodels_ebi:MODEL1006230103
Original: https://www.ebi.ac.uk/biomodels/MODEL1006230103
"""
from __future__ import annotations

from typing import Any

from biosim.contrib.sbml import TelluriumSBMLBioModule


class Heldt2002OrthostaticstressHeartModel(TelluriumSBMLBioModule):
    """Tellurium-backed wrapper for Heldt2002 Orthostatic Stress - Heart."""

    _OBSERVABLE_STRATEGY = 'rateRule'
    _NON_BIOLOGICAL_OBSERVABLES = {'dummy'}
    _TIME_UNIT = 's'
    _SBML_ID = 'MODEL1006230103'
    _TITLE = 'Heldt2002 Orthostatic Stress - Heart'
    _PARAMETER_INPUTS = {'diastolic_elastance': ('Edia',
                         0.19,
                         'mmHg/mL',
                         'Diastolic LV elastance. Sets the chamber compliance during filling.'),
 'heart_rate': ('HR',
                70.0,
                '1/min',
                'Heart rate (beats per minute). Sets the cardiac pacing frequency.'),
 'systolic_elastance': ('Esys',
                        5.6,
                        'mmHg/mL',
                        'Peak systolic LV elastance. Higher values = stronger contractility.')}
    _MULTIPLIER_INPUTS = {}
    _HEADLINE_OUTPUTS = {'elastance': ('E_LV',
               'mmHg/mL',
               'Time-varying left ventricle elastance. The headline output of the contractility '
               'model.')}
    _HEADLINE_WINDOW_S = 2.0
    def visualisation_aux_schema(self) -> dict[str, str]:
        return {"phase_x": "float", "phase_y": "float", "heart_rate_bpm": "float"}

    def visualisation_aux_description(self) -> str:
        return 'Internal phase-portrait payload for the dedicated visualisation model.'

    def visualisation_extra_selections(self) -> list[str]:
        return []

    def _heart_rate_bpm(self) -> float:
        if self._runner is not None:
            try:
                return float(self._runner["HR"])
            except (KeyError, ValueError, TypeError, RuntimeError):
                try:
                    return float(self._runner["hrf"]) * 60.0
                except (KeyError, ValueError, TypeError, RuntimeError):
                    pass
        return 60.0

    def visualisation_aux_payload(self, t: float, latest: dict[str, float]) -> dict[str, Any]:
        heart_rate_bpm = self._heart_rate_bpm()
        period = 60.0 / max(heart_rate_bpm, 1.0)
        return {
            "phase_x": (float(t) % period) / period,
            "phase_y": float(latest.get("E_LV", 0.0)),
            "heart_rate_bpm": float(heart_rate_bpm),
        }

    def __init__(
        self,
        model_path: str = 'data/MODEL1006230103.xml',
        integration_step: float = 0.01,
    ) -> None:
        super().__init__(model_path=model_path, integration_step=integration_step)
